### ISSUE TITLE
No module named 'training.networks.networks'

### ISSUE THREAD

**Issue by xshenhan** [andrew-cr/jump-diffusion#1]
I run the following sampling command with the pretrained checkpoints provided. 

`torchrun --standalone --nproc_per_node=1 generate.py --steps 100 --S_churn 50 --S_noise 1.007 --seeds=0 --batch 1 --cond_endpoints --network=models/score/network-snapshot-001100.pkl --jump_network=models/jump_rate_and_index/network-snapshot-000450.pkl`

> Traceback (most recent call last):
>   File "jump-diffusion/video/generate.py", line 476, in <module>
>     main()
>   File "envs/jump-diffusion/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "envs3/envs/jump-diffusion/lib/python3.9/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "envs/jump-diffusion/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "envs/jump-diffusion/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "jump-diffusion/video/generate.py", line 306, in main
>     data = pickle.load(f)
>   File "jump-diffusion/video/training/networks/__init__.py", line 12, in <module>
>     @persistence.persistent_class
> NameError: name 'persistence' is not defined

so I add the following code to jump-diffusion/video/training/networks/__init__.py

```
import torch
from torch_utils import persistence
```

And then I run the sampling command again.

> Traceback (most recent call last):
>   File "jump-diffusion/video/generate.py", line 476, in <module>
>     main()
>   File "envs/jump-diffusion/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "envs/jump-diffusion/lib/python3.9/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "envs/jump-diffusion/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "envs/jump-diffusion/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "jump-diffusion/video/generate.py", line 306, in main
>     data = pickle.load(f)
>   File "jump-diffusion/video/torch_utils/persistence.py", line 196, in _reconstruct_persistent_obj
>     module = _src_to_module(meta.module_src)
>   File "jump-diffusion/video/torch_utils/persistence.py", line 232, in _src_to_module
>     exec(src, module.__dict__) # pylint: disable=exec-used
>   File "<string>", line 2, in <module>
> ModuleNotFoundError: No module named 'training.networks.networks'

**Comment by andrew-cr** [comment]
Thanks for your interest in the repo! We are currently looking into this problem

**Comment by wsgharvey** [comment]
Thanks @xshenhan for pointing out these issues! 

This PR should address them: https://github.com/andrew-cr/jump-diffusion/pull/2

**Comment by xshenhan** [comment]
It works. Thanks a lot!
