### ISSUE TITLE
Share one illustration of code flow chart for the complicated EGNNMultiHeadJump.forward(…) function.

### ISSUE THREAD

**Issue by MhYao2014** [andrew-cr/jump-diffusion#3]
![molecules_loss_call_EGNNMultiHeadJump_forward_two_times](https://github.com/andrew-cr/jump-diffusion/assets/32889505/18b25731-f50e-46c4-8ca4-8edf40ab0f56)

**Comment by andrew-cr** [comment]
Thanks for making this! Would you be ok if I put it in a readme?

**Comment by MhYao2014** [comment]
> Thanks for making this! Would you be ok if I put it in a readme?

You are welcome.
